return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "tsx",
      "typescript",
      "vim",
      "yaml",
      "css",
      "dockerfile",
      "dart",
      "gitignore",
      "nginx",
      "prisma",
      "rust",
      "scss",
      "sql",
      "toml",
      "vue",
      "xml",
    },
  },
}
